#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Model.DataBaseModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WeiXinData")]
	public partial class ModelContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertWX_CompanyInoformation(WX_CompanyInoformation instance);
    partial void UpdateWX_CompanyInoformation(WX_CompanyInoformation instance);
    partial void DeleteWX_CompanyInoformation(WX_CompanyInoformation instance);
    partial void InsertWX_Contract(WX_Contract instance);
    partial void UpdateWX_Contract(WX_Contract instance);
    partial void DeleteWX_Contract(WX_Contract instance);
    partial void InsertWX_Engineering(WX_Engineering instance);
    partial void UpdateWX_Engineering(WX_Engineering instance);
    partial void DeleteWX_Engineering(WX_Engineering instance);
    partial void InsertWX_ProductionData(WX_ProductionData instance);
    partial void UpdateWX_ProductionData(WX_ProductionData instance);
    partial void DeleteWX_ProductionData(WX_ProductionData instance);
    partial void InsertWX_Transport(WX_Transport instance);
    partial void UpdateWX_Transport(WX_Transport instance);
    partial void DeleteWX_Transport(WX_Transport instance);
    partial void InsertWX_UserInoformation(WX_UserInoformation instance);
    partial void UpdateWX_UserInoformation(WX_UserInoformation instance);
    partial void DeleteWX_UserInoformation(WX_UserInoformation instance);
    #endregion
		
		public ModelContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WX_CompanyInoformation> WX_CompanyInoformation
		{
			get
			{
				return this.GetTable<WX_CompanyInoformation>();
			}
		}
		
		public System.Data.Linq.Table<WX_Contract> WX_Contract
		{
			get
			{
				return this.GetTable<WX_Contract>();
			}
		}
		
		public System.Data.Linq.Table<WX_Engineering> WX_Engineering
		{
			get
			{
				return this.GetTable<WX_Engineering>();
			}
		}
		
		public System.Data.Linq.Table<WX_ProductionData> WX_ProductionData
		{
			get
			{
				return this.GetTable<WX_ProductionData>();
			}
		}
		
		public System.Data.Linq.Table<WX_Transport> WX_Transport
		{
			get
			{
				return this.GetTable<WX_Transport>();
			}
		}
		
		public System.Data.Linq.Table<WX_UserInoformation> WX_UserInoformation
		{
			get
			{
				return this.GetTable<WX_UserInoformation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_CompanyInoformation")]
	public partial class WX_CompanyInoformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KeyId;
		
		private string _CompanyName;
		
		private string _CompanyAdress;
		
		private string _CompanyCode;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyIdChanging(long value);
    partial void OnKeyIdChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnCompanyAdressChanging(string value);
    partial void OnCompanyAdressChanged();
    partial void OnCompanyCodeChanging(string value);
    partial void OnCompanyCodeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public WX_CompanyInoformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(200)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyAdress", DbType="VarChar(500)")]
		public string CompanyAdress
		{
			get
			{
				return this._CompanyAdress;
			}
			set
			{
				if ((this._CompanyAdress != value))
				{
					this.OnCompanyAdressChanging(value);
					this.SendPropertyChanging();
					this._CompanyAdress = value;
					this.SendPropertyChanged("CompanyAdress");
					this.OnCompanyAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyCode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CompanyCode
		{
			get
			{
				return this._CompanyCode;
			}
			set
			{
				if ((this._CompanyCode != value))
				{
					this.OnCompanyCodeChanging(value);
					this.SendPropertyChanging();
					this._CompanyCode = value;
					this.SendPropertyChanged("CompanyCode");
					this.OnCompanyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(1000)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_Contract")]
	public partial class WX_Contract : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KeyId;
		
		private string _EngineeringNo;
		
		private string _ContractNo;
		
		private string _ContractType;
		
		private string _AccountCompany;
		
		private System.Nullable<decimal> _Quantity;
		
		private System.Nullable<decimal> _AmountMoney;
		
		private string _Contacts;
		
		private string _PhoneNumber;
		
		private string _PersonCharge;
		
		private string _Address;
		
		private System.Nullable<System.DateTime> _SignDate;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyIdChanging(long value);
    partial void OnKeyIdChanged();
    partial void OnEngineeringNoChanging(string value);
    partial void OnEngineeringNoChanged();
    partial void OnContractNoChanging(string value);
    partial void OnContractNoChanged();
    partial void OnContractTypeChanging(string value);
    partial void OnContractTypeChanged();
    partial void OnAccountCompanyChanging(string value);
    partial void OnAccountCompanyChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OnAmountMoneyChanging(System.Nullable<decimal> value);
    partial void OnAmountMoneyChanged();
    partial void OnContactsChanging(string value);
    partial void OnContactsChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnPersonChargeChanging(string value);
    partial void OnPersonChargeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSignDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSignDateChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public WX_Contract()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineeringNo", DbType="VarChar(50)")]
		public string EngineeringNo
		{
			get
			{
				return this._EngineeringNo;
			}
			set
			{
				if ((this._EngineeringNo != value))
				{
					this.OnEngineeringNoChanging(value);
					this.SendPropertyChanging();
					this._EngineeringNo = value;
					this.SendPropertyChanged("EngineeringNo");
					this.OnEngineeringNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNo", DbType="VarChar(50)")]
		public string ContractNo
		{
			get
			{
				return this._ContractNo;
			}
			set
			{
				if ((this._ContractNo != value))
				{
					this.OnContractNoChanging(value);
					this.SendPropertyChanging();
					this._ContractNo = value;
					this.SendPropertyChanged("ContractNo");
					this.OnContractNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractType", DbType="VarChar(5)")]
		public string ContractType
		{
			get
			{
				return this._ContractType;
			}
			set
			{
				if ((this._ContractType != value))
				{
					this.OnContractTypeChanging(value);
					this.SendPropertyChanging();
					this._ContractType = value;
					this.SendPropertyChanged("ContractType");
					this.OnContractTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCompany", DbType="VarChar(100)")]
		public string AccountCompany
		{
			get
			{
				return this._AccountCompany;
			}
			set
			{
				if ((this._AccountCompany != value))
				{
					this.OnAccountCompanyChanging(value);
					this.SendPropertyChanging();
					this._AccountCompany = value;
					this.SendPropertyChanged("AccountCompany");
					this.OnAccountCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountMoney", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AmountMoney
		{
			get
			{
				return this._AmountMoney;
			}
			set
			{
				if ((this._AmountMoney != value))
				{
					this.OnAmountMoneyChanging(value);
					this.SendPropertyChanging();
					this._AmountMoney = value;
					this.SendPropertyChanged("AmountMoney");
					this.OnAmountMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacts", DbType="VarChar(20)")]
		public string Contacts
		{
			get
			{
				return this._Contacts;
			}
			set
			{
				if ((this._Contacts != value))
				{
					this.OnContactsChanging(value);
					this.SendPropertyChanging();
					this._Contacts = value;
					this.SendPropertyChanged("Contacts");
					this.OnContactsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonCharge", DbType="VarChar(50)")]
		public string PersonCharge
		{
			get
			{
				return this._PersonCharge;
			}
			set
			{
				if ((this._PersonCharge != value))
				{
					this.OnPersonChargeChanging(value);
					this.SendPropertyChanging();
					this._PersonCharge = value;
					this.SendPropertyChanged("PersonCharge");
					this.OnPersonChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SignDate
		{
			get
			{
				return this._SignDate;
			}
			set
			{
				if ((this._SignDate != value))
				{
					this.OnSignDateChanging(value);
					this.SendPropertyChanging();
					this._SignDate = value;
					this.SendPropertyChanged("SignDate");
					this.OnSignDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_Engineering")]
	public partial class WX_Engineering : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KeyId;
		
		private string _EngineeringNo;
		
		private string _EngineerName;
		
		private string _CompanyCode;
		
		private string _ConstructCompanyName;
		
		private string _ConstructAddress;
		
		private string _ConstructState;
		
		private System.Nullable<System.DateTime> _ConstructDate;
		
		private System.Nullable<System.DateTime> _FinishDate;
		
		private System.Nullable<decimal> _Quantity;
		
		private string _EngineerType;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyIdChanging(long value);
    partial void OnKeyIdChanged();
    partial void OnEngineeringNoChanging(string value);
    partial void OnEngineeringNoChanged();
    partial void OnEngineerNameChanging(string value);
    partial void OnEngineerNameChanged();
    partial void OnCompanyCodeChanging(string value);
    partial void OnCompanyCodeChanged();
    partial void OnConstructCompanyNameChanging(string value);
    partial void OnConstructCompanyNameChanged();
    partial void OnConstructAddressChanging(string value);
    partial void OnConstructAddressChanged();
    partial void OnConstructStateChanging(string value);
    partial void OnConstructStateChanged();
    partial void OnConstructDateChanging(System.Nullable<System.DateTime> value);
    partial void OnConstructDateChanged();
    partial void OnFinishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishDateChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OnEngineerTypeChanging(string value);
    partial void OnEngineerTypeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    #endregion
		
		public WX_Engineering()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineeringNo", DbType="VarChar(50)")]
		public string EngineeringNo
		{
			get
			{
				return this._EngineeringNo;
			}
			set
			{
				if ((this._EngineeringNo != value))
				{
					this.OnEngineeringNoChanging(value);
					this.SendPropertyChanging();
					this._EngineeringNo = value;
					this.SendPropertyChanged("EngineeringNo");
					this.OnEngineeringNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineerName", DbType="VarChar(100)")]
		public string EngineerName
		{
			get
			{
				return this._EngineerName;
			}
			set
			{
				if ((this._EngineerName != value))
				{
					this.OnEngineerNameChanging(value);
					this.SendPropertyChanging();
					this._EngineerName = value;
					this.SendPropertyChanged("EngineerName");
					this.OnEngineerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyCode", DbType="VarChar(100)")]
		public string CompanyCode
		{
			get
			{
				return this._CompanyCode;
			}
			set
			{
				if ((this._CompanyCode != value))
				{
					this.OnCompanyCodeChanging(value);
					this.SendPropertyChanging();
					this._CompanyCode = value;
					this.SendPropertyChanged("CompanyCode");
					this.OnCompanyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConstructCompanyName", DbType="VarChar(100)")]
		public string ConstructCompanyName
		{
			get
			{
				return this._ConstructCompanyName;
			}
			set
			{
				if ((this._ConstructCompanyName != value))
				{
					this.OnConstructCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._ConstructCompanyName = value;
					this.SendPropertyChanged("ConstructCompanyName");
					this.OnConstructCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConstructAddress", DbType="VarChar(500)")]
		public string ConstructAddress
		{
			get
			{
				return this._ConstructAddress;
			}
			set
			{
				if ((this._ConstructAddress != value))
				{
					this.OnConstructAddressChanging(value);
					this.SendPropertyChanging();
					this._ConstructAddress = value;
					this.SendPropertyChanged("ConstructAddress");
					this.OnConstructAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConstructState", DbType="VarChar(10)")]
		public string ConstructState
		{
			get
			{
				return this._ConstructState;
			}
			set
			{
				if ((this._ConstructState != value))
				{
					this.OnConstructStateChanging(value);
					this.SendPropertyChanging();
					this._ConstructState = value;
					this.SendPropertyChanged("ConstructState");
					this.OnConstructStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConstructDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ConstructDate
		{
			get
			{
				return this._ConstructDate;
			}
			set
			{
				if ((this._ConstructDate != value))
				{
					this.OnConstructDateChanging(value);
					this.SendPropertyChanging();
					this._ConstructDate = value;
					this.SendPropertyChanged("ConstructDate");
					this.OnConstructDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishDate
		{
			get
			{
				return this._FinishDate;
			}
			set
			{
				if ((this._FinishDate != value))
				{
					this.OnFinishDateChanging(value);
					this.SendPropertyChanging();
					this._FinishDate = value;
					this.SendPropertyChanged("FinishDate");
					this.OnFinishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineerType", DbType="VarChar(10)")]
		public string EngineerType
		{
			get
			{
				return this._EngineerType;
			}
			set
			{
				if ((this._EngineerType != value))
				{
					this.OnEngineerTypeChanging(value);
					this.SendPropertyChanging();
					this._EngineerType = value;
					this.SendPropertyChanged("EngineerType");
					this.OnEngineerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(100)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_ProductionData")]
	public partial class WX_ProductionData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KeyId;
		
		private string _ContractNo;
		
		private System.Nullable<decimal> _ProduceQuantity;
		
		private string _ConcreteType;
		
		private string _PouringType;
		
		private string _PouringPart;
		
		private System.Nullable<System.DateTime> _PorductionDate;
		
		private string _PersonCharge;
		
		private string _ProductionNo;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyIdChanging(long value);
    partial void OnKeyIdChanged();
    partial void OnContractNoChanging(string value);
    partial void OnContractNoChanged();
    partial void OnProduceQuantityChanging(System.Nullable<decimal> value);
    partial void OnProduceQuantityChanged();
    partial void OnConcreteTypeChanging(string value);
    partial void OnConcreteTypeChanged();
    partial void OnPouringTypeChanging(string value);
    partial void OnPouringTypeChanged();
    partial void OnPouringPartChanging(string value);
    partial void OnPouringPartChanged();
    partial void OnPorductionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPorductionDateChanged();
    partial void OnPersonChargeChanging(string value);
    partial void OnPersonChargeChanged();
    partial void OnProductionNoChanging(string value);
    partial void OnProductionNoChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public WX_ProductionData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNo", DbType="VarChar(50)")]
		public string ContractNo
		{
			get
			{
				return this._ContractNo;
			}
			set
			{
				if ((this._ContractNo != value))
				{
					this.OnContractNoChanging(value);
					this.SendPropertyChanging();
					this._ContractNo = value;
					this.SendPropertyChanged("ContractNo");
					this.OnContractNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduceQuantity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ProduceQuantity
		{
			get
			{
				return this._ProduceQuantity;
			}
			set
			{
				if ((this._ProduceQuantity != value))
				{
					this.OnProduceQuantityChanging(value);
					this.SendPropertyChanging();
					this._ProduceQuantity = value;
					this.SendPropertyChanged("ProduceQuantity");
					this.OnProduceQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConcreteType", DbType="VarChar(50)")]
		public string ConcreteType
		{
			get
			{
				return this._ConcreteType;
			}
			set
			{
				if ((this._ConcreteType != value))
				{
					this.OnConcreteTypeChanging(value);
					this.SendPropertyChanging();
					this._ConcreteType = value;
					this.SendPropertyChanged("ConcreteType");
					this.OnConcreteTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouringType", DbType="VarChar(50)")]
		public string PouringType
		{
			get
			{
				return this._PouringType;
			}
			set
			{
				if ((this._PouringType != value))
				{
					this.OnPouringTypeChanging(value);
					this.SendPropertyChanging();
					this._PouringType = value;
					this.SendPropertyChanged("PouringType");
					this.OnPouringTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouringPart", DbType="VarChar(50)")]
		public string PouringPart
		{
			get
			{
				return this._PouringPart;
			}
			set
			{
				if ((this._PouringPart != value))
				{
					this.OnPouringPartChanging(value);
					this.SendPropertyChanging();
					this._PouringPart = value;
					this.SendPropertyChanged("PouringPart");
					this.OnPouringPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorductionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PorductionDate
		{
			get
			{
				return this._PorductionDate;
			}
			set
			{
				if ((this._PorductionDate != value))
				{
					this.OnPorductionDateChanging(value);
					this.SendPropertyChanging();
					this._PorductionDate = value;
					this.SendPropertyChanged("PorductionDate");
					this.OnPorductionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonCharge", DbType="VarChar(50)")]
		public string PersonCharge
		{
			get
			{
				return this._PersonCharge;
			}
			set
			{
				if ((this._PersonCharge != value))
				{
					this.OnPersonChargeChanging(value);
					this.SendPropertyChanging();
					this._PersonCharge = value;
					this.SendPropertyChanged("PersonCharge");
					this.OnPersonChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionNo", DbType="VarChar(50)")]
		public string ProductionNo
		{
			get
			{
				return this._ProductionNo;
			}
			set
			{
				if ((this._ProductionNo != value))
				{
					this.OnProductionNoChanging(value);
					this.SendPropertyChanging();
					this._ProductionNo = value;
					this.SendPropertyChanged("ProductionNo");
					this.OnProductionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_Transport")]
	public partial class WX_Transport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KeyId;
		
		private string _TransportNo;
		
		private System.Nullable<decimal> _TansportQuantity;
		
		private System.Nullable<decimal> _TransportDistance;
		
		private string _ProductionNo;
		
		private string _ConcreteType;
		
		private string _CarNo;
		
		private string _Driver;
		
		private System.Nullable<System.DateTime> _TransprotDate;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyIdChanging(long value);
    partial void OnKeyIdChanged();
    partial void OnTransportNoChanging(string value);
    partial void OnTransportNoChanged();
    partial void OnTansportQuantityChanging(System.Nullable<decimal> value);
    partial void OnTansportQuantityChanged();
    partial void OnTransportDistanceChanging(System.Nullable<decimal> value);
    partial void OnTransportDistanceChanged();
    partial void OnProductionNoChanging(string value);
    partial void OnProductionNoChanged();
    partial void OnConcreteTypeChanging(string value);
    partial void OnConcreteTypeChanged();
    partial void OnCarNoChanging(string value);
    partial void OnCarNoChanged();
    partial void OnDriverChanging(string value);
    partial void OnDriverChanged();
    partial void OnTransprotDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransprotDateChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public WX_Transport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportNo", DbType="VarChar(50)")]
		public string TransportNo
		{
			get
			{
				return this._TransportNo;
			}
			set
			{
				if ((this._TransportNo != value))
				{
					this.OnTransportNoChanging(value);
					this.SendPropertyChanging();
					this._TransportNo = value;
					this.SendPropertyChanged("TransportNo");
					this.OnTransportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TansportQuantity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TansportQuantity
		{
			get
			{
				return this._TansportQuantity;
			}
			set
			{
				if ((this._TansportQuantity != value))
				{
					this.OnTansportQuantityChanging(value);
					this.SendPropertyChanging();
					this._TansportQuantity = value;
					this.SendPropertyChanged("TansportQuantity");
					this.OnTansportQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportDistance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TransportDistance
		{
			get
			{
				return this._TransportDistance;
			}
			set
			{
				if ((this._TransportDistance != value))
				{
					this.OnTransportDistanceChanging(value);
					this.SendPropertyChanging();
					this._TransportDistance = value;
					this.SendPropertyChanged("TransportDistance");
					this.OnTransportDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionNo", DbType="VarChar(50)")]
		public string ProductionNo
		{
			get
			{
				return this._ProductionNo;
			}
			set
			{
				if ((this._ProductionNo != value))
				{
					this.OnProductionNoChanging(value);
					this.SendPropertyChanging();
					this._ProductionNo = value;
					this.SendPropertyChanged("ProductionNo");
					this.OnProductionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConcreteType", DbType="VarChar(50)")]
		public string ConcreteType
		{
			get
			{
				return this._ConcreteType;
			}
			set
			{
				if ((this._ConcreteType != value))
				{
					this.OnConcreteTypeChanging(value);
					this.SendPropertyChanging();
					this._ConcreteType = value;
					this.SendPropertyChanged("ConcreteType");
					this.OnConcreteTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarNo", DbType="VarChar(50)")]
		public string CarNo
		{
			get
			{
				return this._CarNo;
			}
			set
			{
				if ((this._CarNo != value))
				{
					this.OnCarNoChanging(value);
					this.SendPropertyChanging();
					this._CarNo = value;
					this.SendPropertyChanged("CarNo");
					this.OnCarNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Driver", DbType="VarChar(50)")]
		public string Driver
		{
			get
			{
				return this._Driver;
			}
			set
			{
				if ((this._Driver != value))
				{
					this.OnDriverChanging(value);
					this.SendPropertyChanging();
					this._Driver = value;
					this.SendPropertyChanged("Driver");
					this.OnDriverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransprotDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TransprotDate
		{
			get
			{
				return this._TransprotDate;
			}
			set
			{
				if ((this._TransprotDate != value))
				{
					this.OnTransprotDateChanging(value);
					this.SendPropertyChanging();
					this._TransprotDate = value;
					this.SendPropertyChanged("TransprotDate");
					this.OnTransprotDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_UserInoformation")]
	public partial class WX_UserInoformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KeyId;
		
		private string _LoginName;
		
		private string _LoginPass;
		
		private string _OpenId;
		
		private string _NickName;
		
		private string _TrueName;
		
		private string _Mobile;
		
		private string _CompanyCode;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyIdChanging(long value);
    partial void OnKeyIdChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnLoginPassChanging(string value);
    partial void OnLoginPassChanged();
    partial void OnOpenIdChanging(string value);
    partial void OnOpenIdChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnTrueNameChanging(string value);
    partial void OnTrueNameChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnCompanyCodeChanging(string value);
    partial void OnCompanyCodeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public WX_UserInoformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="VarChar(20)")]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this.OnLoginNameChanging(value);
					this.SendPropertyChanging();
					this._LoginName = value;
					this.SendPropertyChanged("LoginName");
					this.OnLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginPass", DbType="VarChar(100)")]
		public string LoginPass
		{
			get
			{
				return this._LoginPass;
			}
			set
			{
				if ((this._LoginPass != value))
				{
					this.OnLoginPassChanging(value);
					this.SendPropertyChanging();
					this._LoginPass = value;
					this.SendPropertyChanged("LoginPass");
					this.OnLoginPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenId", DbType="VarChar(100)")]
		public string OpenId
		{
			get
			{
				return this._OpenId;
			}
			set
			{
				if ((this._OpenId != value))
				{
					this.OnOpenIdChanging(value);
					this.SendPropertyChanging();
					this._OpenId = value;
					this.SendPropertyChanged("OpenId");
					this.OnOpenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="VarChar(100)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrueName", DbType="VarChar(20)")]
		public string TrueName
		{
			get
			{
				return this._TrueName;
			}
			set
			{
				if ((this._TrueName != value))
				{
					this.OnTrueNameChanging(value);
					this.SendPropertyChanging();
					this._TrueName = value;
					this.SendPropertyChanged("TrueName");
					this.OnTrueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(11)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyCode", DbType="VarChar(100)")]
		public string CompanyCode
		{
			get
			{
				return this._CompanyCode;
			}
			set
			{
				if ((this._CompanyCode != value))
				{
					this.OnCompanyCodeChanging(value);
					this.SendPropertyChanging();
					this._CompanyCode = value;
					this.SendPropertyChanged("CompanyCode");
					this.OnCompanyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(100)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(1000)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
